spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  security:
    user:
      name: admin
      password: admin
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver
